### ISSUE TITLE
Can't "Stop Mapping" a task

### ISSUE THREAD

**Issue by bgirardot-np** [hotosm/tasking-manager#668]
If I checkout a task to map, when I click "Stop Mapping" I get an error.

For example on this project:
http://tasking-manager-staging.eu-west-1.elasticbeanstalk.com/project/2651?task=71

"There was a problem unlocking the task. Task Lock API - unhandled error: list index out of range"

A second attempt to "Stop Mapping" gives a different error message:

"There was a problem unlocking the task. Task Lock API - unhandled error: No row was found for one()"

That same project seems to show other task still locked from 23 days ago along the west border.

Also when running locally I see these error messages:

```
--------------------------------------------------------------------------------
CRITICAL in mapping_apis [/home/bg/tasking-manager/server/api/mapping_apis.py:237]:
Task Lock API - unhandled error: No row was found for one()
--------------------------------------------------------------------------------
127.0.0.1 - - [02/Aug/2017 03:35:54] "POST /api/v1/project/1/task/17/stop-mapping HTTP/1.1" 500 -
```

Also not sure if it is related, but I also see these messages locally:

`127.0.0.1 - - [02/Aug/2017 03:36:26] "GET /api/v1/project/1/has-user-locked-tasks HTTP/1.1" 404 -
`

**Comment by bgirardot-np** [comment]
@hunt3ri Hi Iain, any progress on this item? cheers

**Comment by hunt3ri** [comment]
Hi @bgirardot I've merged the fix into the develop branch - you may need to merge up into Ali's branch to test on the demo site.

As I mentioned in the PR you'll need to run the following update statement to clean up the data caused by the bug

update task_history
set action_text = NULL
where id in (select th.id
from tasks t,
task_history th
where t.id = th.task_id
and t.project_id = th.project_id
and t.locked_by = th.user_id
and t.locked_by is not null
and th.action_text is not null
and t.mapped_by is null
and th.action = 'LOCKED_FOR_MAPPING');

Let me know if there's any further problems.  Thanks

**Comment by bgirardot** [comment]
@hunt3ri Thank you very much! I will start with testing on the staging server and then we can catch up new-styles branch.

**Comment by bgirardot** [comment]
Fixed, thank @hunt3ri

**Comment by bgirardot** [comment]
We still get this error with seemingly increasing fequency lately:

"[2018-03-15 11:33:25,179] CRITICAL in mapping_apis: Task Lock API - unhandled error: No row was found for one()"

**Comment by bgirardot** [comment]
This is related to issue #1045 Please do not close this one. @dakotabenjamin and @smit1678 At some point in time we should examine the sql in here and see if we need to run that code again. We could do the select against the cloned tm3 database and see if there are folks in those states.

I think this is related to why there is never less than 50 people on the tasking manager as well.

**Comment by ethan-nelson** [comment]
Since merging #1223, we have not heard reports of this any more. Please reopen if you continue to experience this issue.
